spring:
  application:
    name: Microservices1

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

hello:
  rel: Chittibabu

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
